- name: install nodejs
  yum:
    name: nodejs
    state: latest
    update_cache: yes
  become: true
  become_method: sudo

- name: Create a app directory if it does not exist
  file:
    path: "/home/ec2-user/app"
    state: directory
    mode: '0755'

- name: Copy package.json
  copy:
    src: "package.json"
    dest: "/home/ec2-user/app/"

- name: Copy index.js
  copy:
    src: "index.js"
    dest: "/home/ec2-user/app/"

- name: Install packages based on package.json.
  npm:
    path: /home/ec2-user/app/

- name: Install Forever process manager
  npm:
    name: forever
    global: yes
  become: true
